# -*- coding: utf-8 -*-
"""Cópia de Aula Visualização de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfBwhKwATLiwnSGAY9qYfT7LACnVY90P

# **Desafios de Visualização de Dados**

Recursos Úteis:

 * Data Viz Project: https://datavizproject.com/input/c/ - Um catálogo visual de gráficos para explorar.

* From Data to Viz: https://www.data-to-viz.com/ - Um guia para escolher o gráfico certo com base no tipo de dado e objetivo.

* Documentação Seaborn: https://seaborn.pydata.org/ - Para detalhes sobre os parâmetros de estilo e plotagem.

* Documentação Matplotlib: https://matplotlib.org/stable/contents.html - Para controle fino sobre elementos do gráfico.

## **0: Configuração Inicial**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configurações padrão para gráficos (para começar limpo)
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)
plt.rcParams["axes.spines.right"] = False
plt.rcParams["axes.spines.top"] = False

print("Bibliotecas importadas e configurações aplicadas!")

"""### 1: Desafios de Decisão

Para cada cenário abaixo, você receberá um conjunto de dados e uma pergunta de negócio. Sua tarefa é:

1. Analisar a pergunta e o tipo de dado.

2. Consultar o Data Viz Project ou From Data to Viz para identificar o tipo de gráfico mais adequado.

3. Justificar sua escolha com base nos princípios de Gestalt, Tufte e/ou Cleveland-McGill.

4. Implementar o gráfico usando matplotlib e seaborn. Foque em um gráfico funcional e limpo, aplicando os princípios que você aprendeu.

Desafio 1.1: Comparação de Vendas por Região

Cenário: Uma empresa de varejo quer comparar o desempenho de vendas de suas quatro regiões no último trimestre para identificar qual delas precisa de mais atenção.
"""

# Dados para o Desafio 1.1
dados_regiao = {
    'Regiao': ['Norte', 'Sul', 'Leste', 'Oeste'],
    'Vendas_Milhoes': [12.5, 18.2, 15.0, 9.8]
}
df_regiao = pd.DataFrame(dados_regiao)
print("\nDataFrame para Desafio 1.1:")
print(df_regiao)

"""Escreva sua justificativa aqui:
1. Tipo de gráfico escolhido: Gráfico de Barras (Bar Chart).
2. Justificativa (Cleveland-McGill, Gestalt): Segundo a Hierarquia de Cleveland e McGill,
a comparação de posição em uma escala comum (topo das barras) é a tarefa perceptiva mais precisa.
A Lei da Proximidade (Gestalt) ajuda a agrupar as categorias visualmente."""

plt.figure(figsize=(8, 5))
sns.barplot(x='Regiao', y='Vendas_Milhoes', data=df_regiao, color='#3498db')
sns.despine()
plt.title('Vendas por Região (Último Trimestre)', loc='left', fontsize=14, pad=15)
plt.ylabel('Vendas (Milhões R$)')
plt.xlabel('')
plt.show()

"""Desafio 1.2: Distribuição de Idades de Clientes

Cenário: Uma equipe de marketing quer entender a distribuição de idade de seus clientes para segmentar campanhas. Eles têm dados de idade de 1000 clientes.
"""

# Dados para o Desafio 1.2
np.random.seed(42)
idades = np.random.normal(loc=35, scale=10, size=1000).astype(int)
idades = idades[(idades >= 18) & (idades <= 70)] # Limitar idades razoáveis
df_idades = pd.DataFrame({'Idade': idades})
print("\nDataFrame para Desafio 1.2 (primeiras 5 linhas):")
print(df_idades.head())

# Escreva sua justificativa aqui:
# 1. Tipo de gráfico escolhido: Histograma ou Gráfico de Densidade (KDE).
# 2. Justificativa (Cleveland-McGill, Gestalt): Histogramas são ideais para mostrar a forma da distribuição (assimetria, picos). A Lei da Continuidade (Gestalt) ajuda a perceber a "curva" da distribuição.

sns.histplot(df_idades['Idade'], bins=15, kde=True, color='#2ecc71')
sns.despine()
plt.title('Distribuição Etária da Base de Clientes', loc='left', fontsize=14)
plt.xlabel('Idade (Anos)')
plt.ylabel('Frequência de Clientes')
plt.show()

"""Desafio 1.3: Tendência de Acessos ao Site

Cenário: A equipe de produto quer monitorar a evolução diária do número de acessos ao site nos últimos 30 dias para identificar padrões ou quedas.
"""

# Dados para o Desafio 1.3
datas = pd.date_range(start='2024-03-01', periods=30)
np.random.seed(42)
acessos = np.random.randint(1000, 5000, 30)
# Simular uma queda nos últimos dias
acessos[-5:] = np.random.randint(500, 1500, 5)
df_acessos = pd.DataFrame({'Data': datas, 'Acessos': acessos})
print("\nDataFrame para Desafio 1.3 (primeiras 5 linhas):")
print(df_acessos.head())

# Escreva sua justificativa aqui:
# 1. Tipo de gráfico escolhido: Gráfico de Linhas (Line Chart).
# 2. Justificativa (Cleveland-McGill, Gestalt): A Lei da Conexão (Gestalt) é a mais forte para indicar continuidade temporal. O olho humano segue a linha para identificar tendências e quebras (como a queda nos últimos 5 dias).

plt.plot(df_acessos['Data'], df_acessos['Acessos'], marker='o', color='#e74c3c', linewidth=2)
sns.despine()
plt.title('Evolução Diária de Acessos (Últimos 30 dias)', loc='left', fontsize=14)
plt.xticks(rotation=45)
plt.show()

"""Desafio 1.4: Relação entre Investimento em Marketing e Vendas

Cenário: A equipe de finanças quer entender se há uma correlação entre o investimento mensal em marketing e o volume de vendas gerado no mesmo mês.
"""

# Dados para o Desafio 1.4
np.random.seed(42)
investimento_marketing = np.random.randint(10000, 50000, 12)
vendas_mensais = investimento_marketing * 5 + np.random.randint(-5000, 5000, 12)
df_marketing_vendas = pd.DataFrame({
    'Investimento_Marketing': investimento_marketing,
    'Vendas_Mensais': vendas_mensais
})
print("\nDataFrame para Desafio 1.4 (primeiras 5 linhas):")
print(df_marketing_vendas.head())

# Escreva sua justificativa aqui:
# 1. Tipo de gráfico escolhido: Gráfico de Dispersão (Scatter Plot).
# 2. Justificativa (Cleveland-McGill, Gestalt):  É o padrão ouro para correlação entre duas variáveis quantitativas. Utiliza a Posição Espacial (Atributo Pré-atentivo), que é o atributo mais preciso para o cérebro detectar padrões de agrupamento ou tendências lineares.

sns.scatterplot(x='Investimento_Marketing', y='Vendas_Mensais', data=df_marketing_vendas, s=100, color='#9b59b6')
sns.despine()
plt.title('Correlação: Investimento em Marketing vs. Vendas', loc='left', fontsize=14)
plt.xlabel('Investimento (R$)')
plt.ylabel('Vendas (R$)')
plt.show()

"""Desafio 1.5: Composição de Mercado por Categoria de Produto

Cenário: Um analista de mercado quer visualizar a proporção de cada categoria de produto no total de vendas da empresa para entender a dominância de certas categorias.
"""

# Dados para o Desafio 1.5
dados_categorias = {
    'Categoria': ['Eletrônicos', 'Vestuário', 'Alimentos', 'Livros', 'Serviços'],
    'Vendas_Milhoes': [35.0, 20.0, 15.0, 10.0, 5.0]
}
df_categorias = pd.DataFrame(dados_categorias)
print("\nDataFrame para Desafio 1.5:")
print(df_categorias)

# Escreva sua justificativa aqui:
# 1. Tipo de gráfico escolhido: Gráfico de Barras (Ordenado) ou Gráfico de Rosca (Donut Chart).
# 2. Justificativa (Cleveland-McGill, Gestalt):  Embora o aluno possa sugerir Pizza, o ideal é um Gráfico de Barras Ordenado. Cleveland e McGill provaram que comparar comprimento é muito mais preciso que comparar ângulos ou áreas. Se usar Pizza, deve ter poucas fatias e rótulos claros.

df_sorted = df_categorias.sort_values('Vendas_Milhoes', ascending=False)
sns.barplot(x='Vendas_Milhoes', y='Categoria', data=df_sorted, color='#f1c40f')
sns.despine(left=True)
plt.title('Participação por Categoria de Produto', loc='left', fontsize=14)
plt.xlabel('Vendas (Milhões R$)')
plt.ylabel('')
plt.show()

"""### Parte 2: Desafios de Refatoração Crítica

Para cada cenário abaixo, você receberá um código Python que gera um gráfico com problemas de design. Sua tarefa é:

1. Analisar o gráfico gerado e identificar pelo menos 3 problemas com base nos princípios de Tufte (Data-Ink Ratio, Lie Factor, Chartjunk), Gestalt (Proximidade, Semelhança, Fechamento, etc.) e/ou Cleveland-McGill (eficácia da codificação).

2. Descrever os problemas identificados.

3. Modificar o código para refatorar o gráfico, aplicando os princípios para torná-lo mais honesto, eficiente e visualmente claro.

Desafio 2.1: Vendas Trimestrais com Eixo Y Enganoso

Cenário: Um gerente de vendas recebeu este gráfico e está preocupado com uma suposta queda drástica nas vendas do Q4.
"""

# Dados para o Desafio 2.1
dados_trimestrais = {
    'Trimestre': ['Q1', 'Q2', 'Q3', 'Q4'],
    'Vendas': [1000, 1050, 1020, 980]
}
df_trimestral = pd.DataFrame(dados_trimestrais)

plt.figure(figsize=(7, 5))
ax = sns.barplot(x='Trimestre', y='Vendas', data=df_trimestral, color='lightcoral')
ax.set_ylim(bottom=950) # Eixo Y começando alto
ax.set_title('Vendas Trimestrais - Último Ano', fontsize=14, fontweight='bold')
ax.set_xlabel('Trimestre')
ax.set_ylabel('Vendas (Unidades)')
ax.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# 1. Problemas identificados:
#    a) Eixo Y não começa em zero (Lie Factor > 1);
#    b) Grade excessiva (Chartjunk);
#    c) Cor "alerta" (vermelho) sem necessidade.

# 2. Seu código Python refatorado:
plt.figure(figsize=(7, 5))
ax = sns.barplot(x='Trimestre', y='Vendas', data=df_trimestral, color='#34495e')
ax.set_ylim(0, 1200) # Correção do Lie Factor
sns.despine(left=True)
plt.title('Vendas Trimestrais: Estabilidade no Desempenho', loc='left')
# Adicionar labels no topo das barras para facilitar a leitura
for p in ax.patches:
    ax.annotate(f'{p.get_height()}', (p.get_x()+0.4, p.get_height()+20), ha='center')
plt.show()

"""Desafio 2.2: Comparação de Produtos com Gráfico de Pizza Lotado

Cenário: A equipe de produto quer ver a proporção de vendas de 8 produtos diferentes, mas o gráfico atual está confuso.
"""

# Dados para o Desafio 2.2
dados_produtos = {
    'Produto': [f'Produto {i}' for i in range(1, 9)],
    'Vendas': [150, 120, 80, 70, 60, 50, 40, 30]
}
df_produtos = pd.DataFrame(dados_produtos)

plt.figure(figsize=(8, 8))
plt.pie(df_produtos['Vendas'], labels=df_produtos['Produto'], autopct='%1.1f%%', startangle=90)
plt.title('Proporção de Vendas por Produto', fontsize=14, fontweight='bold')
plt.show()

# 1. Problemas identificados:
#    a) Muitas fatias (sobrecarga do Sistema
#    b) Difícil comparar fatias de tamanhos similares (Ângulo/Área)
#    c) Legendas poluídas

# 2. Seu código Python refatorado:
df_p = df_produtos.sort_values('Vendas', ascending=False)
sns.barplot(x='Vendas', y='Produto', data=df_p, color='#1abc9c')
sns.despine(left=True)
plt.title('Ranking de Vendas por Produto', loc='left')
plt.show()

"""Desafio 2.3: Desempenho de Funcionários com Cores Aleatórias

Cenário: O RH quer visualizar o desempenho (pontuação de 0 a 100) de 5 funcionários em uma avaliação, mas o gráfico atual usa cores sem sentido.
"""

# Dados para o Desafio 2.3
dados_funcionarios = {
    'Funcionario': ['Ana', 'Bruno', 'Carla', 'Daniel', 'Eva'],
    'Pontuacao': [85, 72, 91, 68, 79]
}
df_funcionarios = pd.DataFrame(dados_funcionarios)

plt.figure(figsize=(7, 5))
cores_aleatorias = ['red', 'green', 'blue', 'purple', 'orange']
ax = sns.barplot(x='Funcionario', y='Pontuacao', data=df_funcionarios, palette=cores_aleatorias)
ax.set_title('Pontuação de Desempenho dos Funcionários', fontsize=14, fontweight='bold')
ax.set_ylim(0, 100)
plt.show()

# 1. Problemas identificados:
#    a) Cores sem significado (viola Gestalt: Semelhança);
#    b) Carga cognitiva alta para processar cada cor;
#    c) Falta de hierarquia visual.s

# 2. Seu código Python refatorado:
# Destacar o melhor (Carla)
cores = ['#bdc3c7' if x < max(df_funcionarios['Pontuacao']) else '#2980b9' for x in df_funcionarios['Pontuacao']]
sns.barplot(x='Funcionario', y='Pontuacao', data=df_funcionarios, palette=cores)
sns.despine()
plt.title('Carla lidera a pontuação de desempenho', loc='left', fontweight='bold')
plt.show()

"""Desafio 2.4: Gráfico de Linhas com Chartjunk Excessivo

Cenário: Um analista de dados criou este gráfico para mostrar a evolução de duas métricas ao longo do tempo, mas ele está muito poluído.
"""

# Dados para o Desafio 2.4
datas_mes = pd.date_range(start='2023-01-01', periods=12, freq='M')
np.random.seed(42)
metrica_a = np.random.randint(50, 150, 12).cumsum()
metrica_b = np.random.randint(40, 130, 12).cumsum()

df_metricas = pd.DataFrame({
    'Data': datas_mes,
    'Metrica_A': metrica_a,
    'Metrica_B': metrica_b
})

plt.figure(figsize=(10, 6))
plt.plot(df_metricas['Data'], df_metricas['Metrica_A'], label='Métrica A', marker='o', linestyle='-', linewidth=2, color='blue')
plt.plot(df_metricas['Data'], df_metricas['Metrica_B'], label='Métrica B', marker='x', linestyle='--', linewidth=2, color='red')

plt.title('Evolução das Métricas A e B', fontsize=16, fontweight='bold')
plt.xlabel('Data', fontsize=12)
plt.ylabel('Valor', fontsize=12)
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.grid(True, linestyle=':', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 1. Problemas identificados:
#    a) Marcadores (o, x) e estilos de linha diferentes criam ruído visual
#    b) Grade muito forte
#    c) Legenda distante.

# 2. Seu código Python refatorado:
plt.plot(df_metricas['Data'], df_metricas['Metrica_A'], label='Métrica A', color='#2980b9', linewidth=3)
plt.plot(df_metricas['Data'], df_metricas['Metrica_B'], label='Métrica B', color='#7f8c8d', linewidth=2, linestyle='--')
sns.despine()
plt.title('Crescimento Sustentado das Métricas A e B', loc='left')
plt.legend(frameon=False)
plt.show()

"""Desafio 2.5: Comparação de Desempenho com Gráfico de Bolhas Confuso

Cenário: Um gerente de produto quer comparar o desempenho de diferentes funcionalidades (Funcionalidade 1 a 5) com base em duas métricas: 'Uso' e 'Satisfação'. O tamanho da bolha representa o 'Impacto'.
"""

# Dados para o Desafio 2.5
dados_funcionalidades = {
    'Funcionalidade': [f'Func {i}' for i in range(1, 6)],
    'Uso': [0.8, 0.6, 0.9, 0.4, 0.7],
    'Satisfacao': [0.9, 0.7, 0.8, 0.5, 0.6],
    'Impacto': [100, 50, 120, 30, 80]
}
df_funcionalidades = pd.DataFrame(dados_funcionalidades)

plt.figure(figsize=(8, 8))
plt.scatter(x=df_funcionalidades['Uso'], y=df_funcionalidades['Satisfacao'],
            s=df_funcionalidades['Impacto']*5, # Multiplicar para bolhas maiores
            alpha=0.7,
            c=np.random.rand(len(df_funcionalidades), 3)) # Cores aleatórias

for i, row in df_funcionalidades.iterrows():
    plt.text(row['Uso'], row['Satisfacao'], row['Funcionalidade'], fontsize=9, ha='center', va='center')

plt.title('Desempenho das Funcionalidades', fontsize=14, fontweight='bold')
plt.xlabel('Uso (0-1)', fontsize=12)
plt.ylabel('Satisfação (0-1)', fontsize=12)
plt.grid(True, linestyle=':', alpha=0.5)
plt.show()

# 1. Problemas identificados:
#    a) Cores aleatórias sem escala
#    b) Tamanho da bolha (Área) é difícil de comparar com precisão
#    c) Rótulos sobrepostos

# 2. Seu código Python refatorado:
plt.scatter(df_funcionalidades['Uso'], df_funcionalidades['Satisfacao'],
            s=df_funcionalidades['Impacto']*10, c=df_funcionalidades['Impacto'],
            cmap='Blues', alpha=0.8, edgecolors='grey')
sns.despine()
# Adicionar labels com cuidado
for i, txt in enumerate(df_funcionalidades['Funcionalidade']):
    plt.annotate(txt, (df_funcionalidades['Uso'][i], df_funcionalidades['Satisfacao'][i]+ 0.02), ha='center')
plt.title('Matriz de Desempenho: Uso vs. Satisfação (Tamanho = Impacto)')
plt.show()